on:
  push:
    tags:
      - 'latest'

jobs:
  release:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup git user so that we can later commit
      uses: fregante/setup-git-user@v1.0.1

    - name: Simulate version generation
      run: echo "::set-output name=tag::v1.0.$(git rev-list --count HEAD)"
      id: target-version

    - name: Create version tag
      run: |
        echo Tagging with ${{ steps.target-version.outputs.tag }}
        git tag -a ${{ steps.target-version.outputs.tag }} -m Release ${{ steps.target-version.outputs.tag }}
        #git push origin ${{ steps.target-version.outputs.tag }}

    - name: I was triggered!
      run: echo hello there
